services:
  backend:
    build: .
    container_name: ai-assistant-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - migrate

  test:
    build: .
    container_name: ai-assistant-test
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -m pytest
    profiles:
      - test
    depends_on:
      - migrate

  migrate:
    build: .
    container_name: ai-assistant-migrate
    env_file:
      - .env
    volumes:
      - .:/app
    command: alembic upgrade head
    restart: "no"
