# fly.toml app configuration file generated for ai-assistant-server on 2025-06-29T04:37:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-assistant-server'
primary_region = 'ewr'

[build]

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  worker = "python -m app.worker"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['worker']
