[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I"]

[tool.ruff.isort]
known-first-party = ["app"]

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
# Default test configuration
addopts = "--tb=short"
testpaths = ["tests"]
asyncio_mode = "auto"
markers = [
    "serial: marks tests to run serially (not in parallel)",
]