"""Add chat_type to Chat model for private/group distinction

Revision ID: 0c39d4b83886
Revises: 3a1e469a145d
Create Date: 2025-06-22 16:32:17.036957

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c39d4b83886"
down_revision: Union[str, Sequence[str], None] = "3a1e469a145d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type before adding the column
    chat_type_enum = sa.Enum("PRIVATE", "GROUP", name="chattype")
    chat_type_enum.create(op.get_bind())
    op.add_column(
        "chats",
        sa.Column(
            "chat_type", chat_type_enum, nullable=False, server_default="PRIVATE"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "chat_type")
    chat_type_enum = sa.Enum("PRIVATE", "GROUP", name="chattype")
    chat_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
