"""Rename user_info_struct to chat_members_struct in messages table

Revision ID: 7ff38a094f4c
Revises: 958721de150a
Create Date: 2025-06-22 16:10:01.788078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ff38a094f4c'
down_revision: Union[str, Sequence[str], None] = '958721de150a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_members_struct', sa.JSON(), nullable=True))
    op.drop_column('messages', 'user_info_struct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_info_struct', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('messages', 'chat_members_struct')
    # ### end Alembic commands ###
